### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by AbubakarKang**
The text is hard to read due to the color having no contrast to the background, so I decided to use the same pinkish color you used for hr as the text color so that they are more visible.

### CODE REVIEW

**Comment by Jeydin** [comment]
You can change the text color the body paragraphs [here](https://github.com/Jeydin/jeydin.github.io/blob/main/card.css#L579)

**Comment by Jeydin** [comment]
I'll try your colors, I'm kinda bad at managing colors

**Comment by Jeydin** [comment]
It kinda blends into the cloud there, the last 2 sentences in the middle paragraph

**Comment by Jeydin** [comment]
@AbubakarKang Ohhh, your repository is not updated with mine, update your repository

**Comment by AbubakarKang** [comment]
Ok I will close this PR and open a new one.

**Pull request closed without merging**
